services:
  - type: web
    name: cafearchive-api
    runtime: python
    repo: https://github.com/chloe-yeo01/cafearchive
    branch: main
    rootDir: backend
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-kor tesseract-ocr-eng
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    plan: free
    envVars:
      - key: PORT
        value: "8000"